name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install Serverless CLI
        run: npm install -g serverless

      - name: Deploy
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            sls deploy --stage production
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            sls deploy --stage staging
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            sls deploy --stage dev
          else
            echo "Not a deployable branch!"
          fi