service: sq-sideseats-back
frameworkVersion: '3'
plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'

functions:
  hello:
    events:  # <-- Add this block
        - http:
            path: hello
            method: get
    handler: src/functions/hello/handler.main # This should match the file and exported function of your hello function

package:
  individually: true

custom:
  myStage: ${self:provider.stage}
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: []
    target: 'node18'
    define:
      'require.resolve': undefined
    platform: 'node'
    concurrency: 10
