name: main

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1  # Change this to your AWS region

jobs:
  dev:
    uses: ./.github/workflows/deploy.yml
    # needs: []
    secrets: inherit
    with:
      environment-name: dev

# jobs:
#   deploy-dev:
#     runs-on: ubuntu-latest
#     if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#     with:
#       environment-name: dev
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - name: Install Serverless CLI
#         run: npm install -g serverless
#       - name: Install dependencies
#         run: npm install
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}
#       - name: Deploy to Dev
#         run: sls deploy --stage dev

  # deploy-stag:
  #   runs-on: ubuntu-latest
  #   needs: deploy-dev
  #   if: github.event_name == 'workflow_dispatch' && github.event.inputs.stageName == 'stag'
  #   with:
  #     environment-name: stag
  #   environment:
  #     name: stag
  #     url: ${{ env.AWS_REGION }} # Add your staging environment URL here if available
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #     - name: Install Serverless CLI
  #       run: npm install -g serverless
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.AWS_REGION }}
  #     - name: Deploy to Stag
  #       run: sls deploy --stage stag

  # deploy-prod:
    # runs-on: ubuntu-latest
    # needs: deploy-stag
    # if: github.event_name == 'workflow_dispatch' && github.event.inputs.stageName == 'prod'
    # with:
    #   environment-name: prod
    # environment:
    #   name: prod
    #   url: ${{ env.AWS_REGION }} # Add your production environment URL here if available
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2
    #   - name: Setup Node.js
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: '14'
    #   - name: Install Serverless CLI
    #     run: npm install -g serverless
    #   - name: Install dependencies
    #     run: npm install
    #   - name: Configure AWS credentials
    #     uses: aws-actions/configure-aws-credentials@v1
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: ${{ env.AWS_REGION }}
    #   - name: Deploy to Prod
    #     run: sls deploy --stage prod
