name: main

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  dev:
    uses: ./.github/workflows/deploy.yml
    # needs: []
    secrets: inherit
    with:
      environment-name: dev
  
  staging:
    uses: ./.github/workflows/deploy.yml
    needs: [ dev ]
    with:
      environment-name: staging
      aws-region: us-east-1
    secrets: inherit

  production:
    uses: ./.github/workflows/deploy.yml
    needs: [ staging ]
    with:
      environment-name: production
      aws-region: us-east-1
    secrets: inherit